### ISSUE TITLE
Entitlements aren't being correctly merged

### ISSUE THREAD

**Issue by superrnovae** [itsnebulalol/permasigner#33] opened 2022-07-11 19:42 UTC
Instead of signing everything with the same entitlements, we could dump the original ones using ldid.
We would also need to check if the uppercase team id is present in some keys, and if it does remove it to get stock values.

**Comment by itsnebulalol** [comment] 2022-07-11 19:43
We merge the entitlements with the original ones. Dylibs and frameworks can’t be signed with entitlements.

**Comment by superrnovae** [comment] 2022-07-11 19:52
> We merge the entitlements with the original ones. Dylibs and frameworks can’t be signed with entitlements.

What I see right now is that the code merges bundle identifier, but it's not always correct, and will sometimes contain an uppercase team id, followed by a dot and original bundle identifier.   

Same thing with keychain access keys. My YouTube app won't stay signed on whether I'm jailbroken or on stock.

**Comment by superrnovae** [comment] 2022-07-11 20:01
I know that. What I meant is that the output youtube deb is missing some entitlements that it originally had. Which makes it impossible for it to stay logged in or open links from other apps.

**Comment by superrnovae** [comment] 2022-07-11 20:06
Well, I got my ipa from appdb. I haven't touched it with neither altstore nor sideloadly.

**Comment by itsnebulalol** [comment] 2022-07-11 20:07
It doesn’t seem like ldid is properly merging the entitlements, check entitlements.xml

**Comment by superrnovae** [comment] 2022-07-11 20:13
I don't find the code where it merges the entitlements. All I see is the replacement of {APP_BUNDLE} followed with signing of application.

**Comment by itsnebulalol** [comment] 2022-07-11 20:14
`./ldid -S{tmpfolder}/entitlements.plist -M -Kdev_certificate.p12 '{full_path}'`
-M combined with -S merges the entitlements

**Comment by superrnovae** [comment] 2022-07-11 20:15
Oh, I was wrong. Nevermind, I'm just dumb. I forgot my ipa was missing the entitlements in the first place.

**Comment by superrnovae** [comment] 2022-07-11 20:19
I just checked with the proper IPA this time, and it doesn't seem to merge with the existing ones.
Here are the outputs:
   
Before:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.networking.wifi-info</key>
	<true/>
	<key>keychain-access-groups</key>
	<array>
		<string>EQHXZ8M8AV.com.google.ios.youtube</string>
		<string>EQHXZ8M8AV.com.google.common.SSO</string>
	</array>
	<key>com.apple.developer.networking.multicast</key>
	<true/>
	<key>application-identifier</key>
	<string>EQHXZ8M8AV.com.google.ios.youtube</string>
	<key>aps-environment</key>
	<string>production</string>
	<key>com.apple.developer.coremedia.allow-alternate-video-decoder-selection</key>
	<true/>
	<key>com.apple.developer.usernotifications.time-sensitive</key>
	<true/>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:www.youtube.com</string>
		<string>applinks:youtu.be</string>
		<string>applinks:youtube.com</string>
		<string>applinks:m.youtube.com</string>
	</array>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.com.google.YouTube</string>
		<string>group.com.google.common</string>
	</array>
</dict>
</plist>
```

After: 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.iokit-user-client-class</key>
	<array>
		<string>IOUserClient</string>
	</array>
	<key>platform-application</key>
	<true/>
	<key>get-task-allow</key>
	<true/>
	<key>keychain-access-groups</key>
	<array>
		<string>com.google.ios.youtube</string>
	</array>
	<key>application-identifier</key>
	<string>com.google.ios.youtube</string>
	<key>aps-environment</key>
	<string>production</string>
	<key>com.apple.developer.usernotifications.time-sensitive</key>
	<true/>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>group.com.google.ios.youtube</string>
	</array>
</dict>
</plist>

```

**Comment by itsnebulalol** [comment] 2022-07-11 20:21
Yep, i see, I'll get this checked out by the procursus team.

**Comment by superrnovae** [comment] 2022-07-11 20:23
It does, it's v2.1.5-procursus3. Thank you!

**Comment by itsnebulalol** [comment] 2022-07-12 23:22
After some testing, entitlements are merged fine for me.
```
nebula@Apple-Thing ~ % cd /Users/nebula/Downloads/Payload/YouTube.app 
nebula@Apple-Thing YouTube.app % ldid -e YouTube
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>com.apple.developer.networking.wifi-info</key>
        <true/>
        <key>keychain-access-groups</key>
        <array>
                <string>EQHXZ8M8AV.com.google.ios.youtube</string>
                <string>EQHXZ8M8AV.com.google.common.SSO</string>
        </array>
        <key>com.apple.developer.networking.multicast</key>
        <true/>
        <key>application-identifier</key>
        <string>EQHXZ8M8AV.com.google.ios.youtube</string>
        <key>aps-environment</key>
        <string>production</string>
        <key>com.apple.developer.coremedia.allow-alternate-video-decoder-selection</key>
        <true/>
        <key>com.apple.developer.usernotifications.time-sensitive</key>
        <true/>
        <key>com.apple.developer.associated-domains</key>
        <array>
                <string>applinks:www.youtube.com</string>
                <string>applinks:youtu.be</string>
                <string>applinks:youtube.com</string>
                <string>applinks:m.youtube.com</string>
        </array>
        <key>com.apple.security.application-groups</key>
        <array>
                <string>group.com.google.YouTube</string>
                <string>group.com.google.common</string>
        </array>
</dict>
</plist>%                                                                                                        
nebula@Apple-Thing YouTube.app % cp YouTube Test   
nebula@Apple-Thing YouTube.app % ldid -S/Users/nebula/Code/permasign/entitlements.plist -M -K/Users/nebula/Code/permasign/dev_certificate.p12 Test
nebula@Apple-Thing YouTube.app % ldid -e Test
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>com.apple.developer.networking.wifi-info</key>
        <true/>
        <key>keychain-access-groups</key>
        <array>
                <string>{APP_BUNDLE}</string>
        </array>
        <key>com.apple.developer.networking.multicast</key>
        <true/>
        <key>application-identifier</key>
        <string>{APP_BUNDLE}</string>
        <key>aps-environment</key>
        <string>production</string>
        <key>com.apple.developer.coremedia.allow-alternate-video-decoder-selection</key>
        <true/>
        <key>com.apple.developer.usernotifications.time-sensitive</key>
        <true/>
        <key>com.apple.developer.associated-domains</key>
        <array>
                <string>applinks:www.youtube.com</string>
                <string>applinks:youtu.be</string>
                <string>applinks:youtube.com</string>
                <string>applinks:m.youtube.com</string>
        </array>
        <key>com.apple.security.application-groups</key>
        <array>
                <string>group.{APP_BUNDLE}</string>
        </array>
        <key>com.apple.security.iokit-user-client-class</key>
        <array>
                <string>IOUserClient</string>
        </array>
        <key>platform-application</key>
        <true/>
        <key>get-task-allow</key>
        <true/>
</dict>
</plist>
nebula@Apple-Thing YouTube.app %
```
So this is not a problem with ldid. I'm going to do some more testing with the script and see what the problem is.

**Comment by superrnovae** [comment] 2022-07-13 07:26
Seems like it is being merged on macOS, so probably a Linux issue.

Another thing is keychain-access-groups key is broken now and so is the security/groups key too. So YouTube won't stay logged in as a result. It won't be able to persist the credentials.

**Comment by itsnebulalol** [comment] 2022-07-13 17:21
I’m using macOS. It might be a better idea to just use -s to keep the original entitlements.

I cannot get uYou+ to run on my device when permasigned, but i know it works for other people.

**Comment by superrnovae** [comment] 2022-07-13 18:14
Btw just tested and uYou+ is working when permasigning on Linux.

**Comment by superrnovae** [comment] 2022-07-14 14:00
Just found out I had another binary of ldid that came with the ios toolchain and was somehow present in path. 
It's outdated and doesn't support -M flag.

**Comment by superrnovae** [comment] 2022-07-19 18:31
> So this is not a problem with ldid. I'm going to do some more testing with the script and see what the problem is.

It works because you're passing an executable to ldid, and not the app directory like the script does. When the directory is passed it replaces the entitlements, instead of merging them.

It can be easily fixed though.

**Comment by superrnovae** [comment] 2022-07-20 07:39
It was fixed [upstream](https://github.com/ProcursusTeam/ldid/commit/f2eb981cf8d20ab013d559fa7d383e656954f12d).

**Comment by itsnebulalol** [comment] 2022-07-22 23:54
Just waiting on the ldid release I guess?

**Comment by superrnovae** [comment] 2022-07-22 23:59
> Just waiting on the ldid release I guess? It will also have -P support.
Yup, we won't have to sign dylibs and frameworks on macos and linux anymore.

**Comment by itsnebulalol** [comment] 2022-07-23 00:00
Yep, do you have a discord by the way?

**Comment by superrnovae** [comment] 2022-07-23 08:33
> Yep, do you have a discord account by the way? If so, what is the tag?

it's supernova#2142

**Comment by itsnebulalol** [comment] 2022-07-23 15:39
Closing this as ldid procursus5 was released.

**Comment by itsnebulalol** [comment] 2022-07-23 15:39
> I do, it's supernova#2142

I’ve sent you a friend request

**Closed by itsnebulalol** 2022-07-23 15:39 UTC
Labels: bug
